language: node_js
matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "1"
    - node_js: "2"
    - node_js: "3"
    - node_js: "4"
      after_success:
      - cd dest
      - git add -A
      - git commit -m "update $TRAVIS_COMMIT"
      - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && git push --quiet https://$GH_TOKEN@github.com/RecoTwExplorer/RecoTwExplorer.git gh-pages 2> /dev/null'
    - node_js: "4"
      install:
        - npm install -g npm@3
        - npm install
  allow_failures:
    - node_js: "0.8"
    - node_js: "0.11"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
env:
  global:
    - GIT_COMMITTER_NAME="Travis ci"
    - GIT_COMMITTER_EMAIL=noreply@github.com
    - GIT_AUTHOR_NAME="Travis ci"
    - GIT_AUTHOR_EMAIL=noreply@github.com
    - secure: "iLUUc/LmjRCozVzudYdTk2nkhonLZ5BL2acguMjGV5ds2Wh6rcy+qvqOE456MpU+sggXtJHwPD5A8cJZyo++iWLUSvOB9GBdi3tfXCsW6/VofhMU8sOzpmGNbJdnTUn6XF0CY06Dw9xVLIaasHl/Zc3Y5g/csJbB+ab+pv1Naaw="
before_script:
  - npm install -g gulp
  - git clone --quiet -b gh-pages https://github.com/RecoTwExplorer/RecoTwExplorer dest
  - pushd dest
  - git checkout gh-pages
  - popd
script: gulp full
notifications:
  slack: recotw:PoaO7IkinDg2n1hsefTqraCy
