language: node_js
node_js:
  - "0.10"
env:
  global:
    - GIT_COMMITTER_NAME="Travis ci"
    - GIT_COMMITTER_EMAIL=noreply@github.com
    - GIT_AUTHOR_NAME="Travis ci"
    - GIT_AUTHOR_EMAIL=noreply@github.com
    - secure: "iLUUc/LmjRCozVzudYdTk2nkhonLZ5BL2acguMjGV5ds2Wh6rcy+qvqOE456MpU+sggXtJHwPD5A8cJZyo++iWLUSvOB9GBdi3tfXCsW6/VofhMU8sOzpmGNbJdnTUn6XF0CY06Dw9xVLIaasHl/Zc3Y5g/csJbB+ab+pv1Naaw="
before_script:
  - npm install -g gulp
  - git clone --quiet -b gh-pages https://github.com/RecoTwExplorer/RecoTwExplorer dest
  - pushd dest
  - git checkout gh-pages
  - popd
script: gulp
after_success:
  - cd dest
  - git add -A
  - git commit -m "update $TRAVIS_COMMIT"
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && git push --quiet https://$GH_TOKEN@github.com/RecoTwExplorer/RecoTwExplorer.git gh-pages 2> /dev/null'
