version: "3.8"

services:
  app:
    image: node:14.10.1-alpine
    command: npx webpack-dev-server
    working_dir: /usr/src
    environment:
      RECOTW_API_HOST: "${RECOTW_API_HOST-stub}"
    networks:
      - recotw
    volumes:
      - .:/usr/src

networks:
  recotw:
    name: recotw
